import { mirrorKeys } from "@stores/utils";

const resourceKeyActions = mirrorKeys([
  "FETCH_RESOURCE_KEYS_REQUESTED",
  "FETCH_RESOURCE_KEYS_PENDING",
  "FETCH_RESOURCE_KEYS_SUCCEEDED",
  "FETCH_RESOURCE_KEYS_FAILED",

  "CREATE_RESOURCE_KEY_REQUESTED",
  "CREATE_RESOURCE_KEY_SUCCEEDED",
  "REVOKE_RESOURCE_KEY_REQUESTED",
  "REVOKE_RESOURCE_KEY_SUCCEEDED",
  "DELETE_RESOURCE_KEY_REQUESTED",
  "DELETE_RESOURCE_KEY_SUCCEEDED",

  "RESOURCE_KEY_ACTION_FAILED",
  "DISMISS_REVEALED_RESOURCE_KEY",
  "RESET_RESOURCE_KEYS",
] as const);

export default resourceKeyActions;
