//! Prints EIP-712/EIP-191 guarantee-request digests for fixed inputs, as JSON.
//! Used to (re)generate the Python SDK's cross-language digest fixture:
//! `cargo run --example digest_vectors > ../sdk-python/tests/fixtures/digest_vectors.json`

use alloy::primitives::{Bytes, B256, U256};
use rpc::{
    CorePublicParameters, PaymentGuaranteeRequestClaims, ValidationRequirement,
};
use sdk_4mica::digest::{eip191_digest_for_claims, eip712_digest_for_claims};

fn params() -> CorePublicParameters {
    CorePublicParameters {
        public_key: vec![0u8; 48],
        contract_address: "0x00000000000000000000000000000000C04e4A1c".to_string(),
        ethereum_http_rpc_url: String::new(),
        eip712_name: "4mica".to_string(),
        eip712_version: "1".to_string(),
        chain_id: 84532,
        supported_guarantee_versions: vec![1],
        guarantee_domain_separator: String::new(),
        guarantee_domains: Vec::new(),
        core_domain_separator: String::new(),
        validators: Vec::new(),
    }
}

fn claims() -> PaymentGuaranteeRequestClaims {
    PaymentGuaranteeRequestClaims::new(
        "0x1234567890123456789012345678901234567890".to_string(),
        "0x00000000000000000000000000000000000000Be".to_string(),
        U256::from(7u64),
        U256::from(1000u64),
        1_700_000_000,
        None,
    )
}

fn validated_claims() -> PaymentGuaranteeRequestClaims {
    claims().with_validation(ValidationRequirement {
        validator: "eip155:84532:0x1111111111111111111111111111111111111111".to_string(),
        subject: B256::repeat_byte(0x42),
        deadline: Some(1_700_000_600),
        params: Bytes::from(vec![0xde, 0xad, 0xbe, 0xef]),
    })
}

fn main() {
    let params = params();
    let plain = claims();
    let validated = validated_claims();

    let user = "0x1234567890123456789012345678901234567890".parse().unwrap();
    let recipient = "0x00000000000000000000000000000000000000Be".parse().unwrap();

    let out = serde_json::json!({
        "_comment": "Generated by packages/sdk-rust/examples/digest_vectors.rs. Do not edit by hand.",
        "params": {
            "contract_address": params.contract_address,
            "eip712_name": params.eip712_name,
            "eip712_version": params.eip712_version,
            "chain_id": params.chain_id,
        },
        "plain": {
            "claims": plain,
            "eip712_digest": eip712_digest_for_claims(&params, &plain).unwrap(),
            "eip191_digest": eip191_digest_for_claims(&plain, user, recipient).unwrap(),
        },
        "validated": {
            "claims": validated,
            "eip712_digest": eip712_digest_for_claims(&params, &validated).unwrap(),
            "eip191_digest": eip191_digest_for_claims(&validated, user, recipient).unwrap(),
        },
    });
    println!("{}", serde_json::to_string_pretty(&out).unwrap());
}
