import { mirrorKeys } from "@stores/utils";

const customerActions = mirrorKeys([
  "FETCH_CUSTOMERS_REQUESTED",
  "FETCH_CUSTOMERS_PENDING",
  "FETCH_CUSTOMERS_SUCCEEDED",
  "FETCH_CUSTOMERS_FAILED",

  "CREATE_CUSTOMER_REQUESTED",
  "CREATE_CUSTOMER_SUCCEEDED",
  "UPDATE_CUSTOMER_REQUESTED",
  "UPDATE_CUSTOMER_SUCCEEDED",
  "FETCH_CUSTOMER_CREDIT_REQUESTED",
  "FETCH_CUSTOMER_CREDIT_SUCCEEDED",
  "GRANT_CUSTOMER_CREDIT_REQUESTED",
  "ZERO_CUSTOMER_CREDIT_REQUESTED",
  "SET_CUSTOMER_POLICY_REQUESTED",
  "SET_CUSTOMER_POLICY_SUCCEEDED",
  "RESET_CUSTOMER_USAGE_REQUESTED",
  "SET_CUSTOMER_STATUS_REQUESTED",
  "SET_CUSTOMER_STATUS_SUCCEEDED",
  "DELETE_CUSTOMER_REQUESTED",
  "DELETE_CUSTOMER_SUCCEEDED",
  "BATCH_DELETE_CUSTOMERS_REQUESTED",
  "BATCH_DELETE_CUSTOMERS_SUCCEEDED",

  "ADD_CUSTOMER_IDENTITY_REQUESTED",
  "UPDATE_CUSTOMER_IDENTITY_REQUESTED",
  "REMOVE_CUSTOMER_IDENTITY_REQUESTED",
  "CUSTOMER_IDENTITY_CHANGED",

  "FETCH_CUSTOMER_DETAIL_REQUESTED",
  "FETCH_CUSTOMER_DETAIL_PENDING",
  "FETCH_CUSTOMER_DETAIL_SUCCEEDED",
  "FETCH_CUSTOMER_DETAIL_FAILED",

  "FETCH_CUSTOMER_ACTIVITY_REQUESTED",
  "FETCH_CUSTOMER_ACTIVITY_SUCCEEDED",
  "SET_CUSTOMER_ACTIVITY_PAGE",

  "SET_CUSTOMER_FILTERS",
  "SET_CUSTOMER_PAGE",
  "TOGGLE_CUSTOMER_SELECTED",
  "SET_CUSTOMER_SELECTION",
  "CLEAR_CUSTOMER_SELECTION",

  "CUSTOMER_ACTION_FAILED",
  "CLEAR_CUSTOMER_ISSUES",
  "RESET_CUSTOMER_DETAIL",
] as const);

export default customerActions;
