import { mirrorKeys } from "@stores/utils";

const developerActions = mirrorKeys([
  "FETCH_DEVELOPER_REQUESTED",
  "FETCH_DEVELOPER_PENDING",
  "FETCH_DEVELOPER_SUCCEEDED",
  "FETCH_DEVELOPER_FAILED",

  "CREATE_API_KEY_REQUESTED",
  "CREATE_API_KEY_SUCCEEDED",
  "RENAME_API_KEY_REQUESTED",
  "RENAME_API_KEY_SUCCEEDED",
  "REVOKE_API_KEY_REQUESTED",
  "REVOKE_API_KEY_SUCCEEDED",
  "DELETE_API_KEY_REQUESTED",
  "DELETE_API_KEY_SUCCEEDED",

  "CREATE_WEBHOOK_REQUESTED",
  "CREATE_WEBHOOK_SUCCEEDED",
  "UPDATE_WEBHOOK_REQUESTED",
  "UPDATE_WEBHOOK_SUCCEEDED",
  "ROTATE_WEBHOOK_SECRET_REQUESTED",
  "ROTATE_WEBHOOK_SECRET_SUCCEEDED",
  "DELETE_WEBHOOK_REQUESTED",
  "DELETE_WEBHOOK_SUCCEEDED",

  "DEVELOPER_ACTION_FAILED",
  "DISMISS_REVEALED_SECRET",
] as const);

export default developerActions;
