"""Digest parity with the Rust SDK.

``digest_vectors.json`` is generated by
``cargo run --example digest_vectors`` in ``packages/sdk-rust`` — the same
code core verifies against. A drift here means signatures stop verifying
on the server, so these are exact-match tests.
"""

import json
from pathlib import Path

from eth_account.messages import encode_typed_data
from eth_utils import keccak

from fourmica_sdk.digest import (
    eip191_payload_for_claims,
    eip712_message_for_claims,
    encode_type_string,
)
from fourmica_sdk.models import (
    CorePublicParameters,
    PaymentGuaranteeRequestClaims,
    ValidationRequirement,
)

FIXTURES = Path(__file__).parent / "fixtures"

# Canonical EIP-712 encodeType strings, matching
# crates/rpc/src/guarantee/signing.rs. Field order/type drift makes the
# produced signature unverifiable on-chain — pin them exactly.
CLAIMS_V1_TYPE = (
    "SolGuaranteeRequestClaimsV1(address user,address recipient,uint256 reqId,"
    "uint256 amount,address asset,uint64 timestamp)"
)
VALIDATED_CLAIMS_V1_TYPE = (
    "SolValidatedGuaranteeRequestClaimsV1(address user,address recipient,"
    "uint256 reqId,uint256 amount,address asset,uint64 timestamp,"
    "SolValidation validation)"
    "SolValidation(string validator,bytes32 subject,uint64 deadline,bytes params)"
)


def load_vectors():
    return json.loads((FIXTURES / "digest_vectors.json").read_text())


def build_params(fx) -> CorePublicParameters:
    return CorePublicParameters(
        public_key=b"\x00" * 48,
        contract_address=fx["params"]["contract_address"],
        eip712_name=fx["params"]["eip712_name"],
        eip712_version=fx["params"]["eip712_version"],
        chain_id=fx["params"]["chain_id"],
    )


def build_claims(raw) -> PaymentGuaranteeRequestClaims:
    validation = None
    if "validation" in raw:
        v = raw["validation"]
        validation = ValidationRequirement(
            validator=v["validator"],
            subject=v["subject"],
            deadline=v.get("deadline"),
            params=v.get("params", "0x"),
        )
    return PaymentGuaranteeRequestClaims(
        user_address=raw["user_address"],
        recipient_address=raw["recipient_address"],
        req_id=raw["req_id"],
        amount=raw["amount"],
        asset_address=raw["asset_address"],
        timestamp=raw["timestamp"],
        validation=validation,
    )


def eip712_digest(full_message: dict) -> str:
    msg = encode_typed_data(full_message=full_message)
    return "0x" + keccak(b"\x19" + msg.version + msg.header + msg.body).hex()


def eip191_digest(payload: bytes) -> str:
    prefixed = f"\x19Ethereum Signed Message:\n{len(payload)}".encode() + payload
    return "0x" + keccak(prefixed).hex()


def test_encode_type_strings_are_pinned():
    assert encode_type_string("SolGuaranteeRequestClaimsV1") == CLAIMS_V1_TYPE
    assert (
        encode_type_string("SolValidatedGuaranteeRequestClaimsV1")
        == VALIDATED_CLAIMS_V1_TYPE
    )


def test_domain_includes_verifying_contract():
    fx = load_vectors()
    message = eip712_message_for_claims(
        build_params(fx), build_claims(fx["plain"]["claims"])
    )
    assert message["domain"]["verifyingContract"] == fx["params"]["contract_address"]
    assert [f["name"] for f in message["types"]["EIP712Domain"]] == [
        "name",
        "version",
        "chainId",
        "verifyingContract",
    ]


def test_plain_digests_match_rust():
    fx = load_vectors()
    params = build_params(fx)
    claims = build_claims(fx["plain"]["claims"])

    assert (
        eip712_digest(eip712_message_for_claims(params, claims))
        == fx["plain"]["eip712_digest"]
    )
    assert (
        eip191_digest(eip191_payload_for_claims(claims)) == fx["plain"]["eip191_digest"]
    )


def test_validated_digests_match_rust():
    fx = load_vectors()
    params = build_params(fx)
    claims = build_claims(fx["validated"]["claims"])
    assert claims.validation is not None

    assert (
        eip712_digest(eip712_message_for_claims(params, claims))
        == fx["validated"]["eip712_digest"]
    )
    assert (
        eip191_digest(eip191_payload_for_claims(claims))
        == fx["validated"]["eip191_digest"]
    )


def test_validated_and_plain_digests_differ():
    fx = load_vectors()
    assert fx["plain"]["eip712_digest"] != fx["validated"]["eip712_digest"]
