export const links = {
  home: "/",
  about: "/about",
  agentsRegister: "/agents/register",
  careers: "/careers",
  interactiveProtocol: "/interactive-protocol",
  leadership: "/leadership",
  privacy: "/privacy",
  register: "/register",
  resources: "/resources",
  blog: "/resources/blog",
  gettingPaidBy4Mica: "/resources/blog/getting-paid-by-4mica",
  how4MicaWorks: "/resources/blog/how-4mica-works",
  payingWith4Mica: "/resources/blog/paying-with-4mica",
  legacyBlogPost: "/resources/blog/1",
  onePager: "/resources/one-pager",
  technicalDocs: "/resources/technical-docs",
  roadmap: "/roadmap",
  terms: "/terms",
} as const;
