import { mirrorKeys } from "@stores/utils";

const userActions = mirrorKeys([
  "FETCH_USER_REQUESTED",
  "FETCH_USER_PENDING",
  "FETCH_USER_SUCCEEDED",
  "FETCH_USER_FAILED",

  "UPDATE_PROFILE_REQUESTED",
  "UPDATE_ACCOUNT_REQUESTED",
  "UPDATE_NOTIFICATIONS_REQUESTED",
  "UPDATE_USER_SUCCEEDED",
  "UPDATE_USER_FAILED",

  "UPDATE_BUSINESS_REQUESTED",
  "UPDATE_BUSINESS_SUCCEEDED",
  "UPDATE_BUSINESS_FAILED",

  "CLEAR_VALIDATION_ISSUES",
] as const);

export default userActions;
