// Regenerate src/abi/core4mica.ts and src/abi/clearinghouse.ts from the
// monorepo's contracts/abi/*.json.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const repoRoot = resolve(pkgRoot, "../..");
const abiDir = resolve(repoRoot, "contracts/abi");
const source = readFileSync(resolve(abiDir, "SOURCE"), "utf8").trim();

const targets = [
  {
    json: "Core4Mica.json",
    out: "src/abi/core4mica.ts",
    name: "core4micaAbi",
    doc: "Core4Mica contract ABI.",
  },
  {
    json: "ClearingHouse.json",
    out: "src/abi/clearinghouse.ts",
    name: "clearingHouseAbi",
    doc: "ClearingHouse contract ABI.",
  },
];

const written = [];
for (const target of targets) {
  const { abi } = JSON.parse(
    readFileSync(resolve(abiDir, target.json), "utf8"),
  );
  const file = [
    "/**",
    ` * ${target.doc} Generated by scripts/refresh-abis.sh; do not edit.`,
    ` * Source: ${source}`,
    " */",
    'import type { Abi } from "viem";',
    "",
    `export const ${target.name} = ${JSON.stringify(abi, null, 2)} as const satisfies Abi;`,
    "",
  ].join("\n");
  const outPath = resolve(pkgRoot, target.out);
  writeFileSync(outPath, file);
  written.push(outPath);
}

execFileSync("pnpm", ["exec", "biome", "format", "--write", ...written], {
  cwd: repoRoot,
  stdio: "inherit",
});
for (const path of written) console.log(`wrote ${path}`);
