import { mirrorKeys } from "@stores/utils";

const apiListingActions = mirrorKeys([
  "FETCH_API_LISTINGS_REQUESTED",
  "FETCH_API_LISTINGS_PENDING",
  "FETCH_API_LISTINGS_SUCCEEDED",
  "FETCH_API_LISTINGS_FAILED",

  "CREATE_API_LISTING_REQUESTED",
  "CREATE_API_LISTING_SUCCEEDED",
  "UPDATE_API_LISTING_REQUESTED",
  "UPDATE_API_LISTING_SUCCEEDED",
  "REPLACE_API_ENDPOINTS_REQUESTED",
  "REPLACE_API_ENDPOINTS_SUCCEEDED",
  "PUBLISH_API_LISTING_REQUESTED",
  "PUBLISH_API_LISTING_SUCCEEDED",
  "DELETE_API_LISTING_REQUESTED",
  "DELETE_API_LISTING_SUCCEEDED",
  "BATCH_DELETE_API_LISTINGS_REQUESTED",
  "BATCH_DELETE_API_LISTINGS_SUCCEEDED",

  "SET_API_LISTING_FILTERS",
  "SET_API_LISTING_PAGE",
  "TOGGLE_API_LISTING_SELECTED",
  "SET_API_LISTING_SELECTION",
  "CLEAR_API_LISTING_SELECTION",

  "API_LISTING_ACTION_FAILED",
  "CLEAR_API_LISTING_ISSUES",
] as const);

export default apiListingActions;
