export {
  EmailClient,
  type EmailClientLogger,
  type EmailClientOptions,
  type SendEmailResult,
} from "./client";
export { EmailClientError, type EmailValidationIssue } from "./errors";
export {
  type AccountDeletedPayload,
  AccountDeletedSchema,
  type ActionRequiredPayload,
  ActionRequiredSchema,
  type AgentCreatedPayload,
  AgentCreatedSchema,
  type AnnouncementPayload,
  AnnouncementSchema,
  type BaseEmailPayload,
  BaseEmailSchema,
  type CreditLimitChangedPayload,
  CreditLimitChangedSchema,
  type DisputeCreatedPayload,
  DisputeCreatedSchema,
  type Money,
  type PaymentSucceededPayload,
  PaymentSucceededSchema,
  type PayoutPaidPayload,
  PayoutPaidSchema,
  type ReceiptPayload,
  ReceiptSchema,
  type SubscriptionExpirationPayload,
  SubscriptionExpirationSchema,
  type SubscriptionRenewedPayload,
  SubscriptionRenewedSchema,
  type WaitlistConfirmationPayload,
  WaitlistConfirmationSchema,
  type WaitlistInvitationPayload,
  WaitlistInvitationSchema,
  type WeeklyReportPayload,
  WeeklyReportSchema,
  type WelcomePayload,
  WelcomeSchema,
  type WorkspaceInvitePayload,
  WorkspaceInviteSchema,
} from "./payloads";
export {
  isTemplateId,
  type TemplateId,
  type TemplatePayload,
  type TemplateProps,
  type TemplateSchemas,
  templateIds,
  templatePath,
  templateSchemas,
} from "./templates";
