import { mirrorKeys } from "@stores/utils";

const walletActions = mirrorKeys([
  "FETCH_WALLETS_REQUESTED",
  "FETCH_WALLETS_PENDING",
  "FETCH_WALLETS_SUCCEEDED",
  "FETCH_WALLETS_FAILED",

  "CREATE_WALLET_REQUESTED",
  "CREATE_WALLET_SUCCEEDED",
  "UPDATE_WALLET_REQUESTED",
  "UPDATE_WALLET_SUCCEEDED",
  "DELETE_WALLET_REQUESTED",
  "DELETE_WALLET_SUCCEEDED",
  "BATCH_DELETE_WALLETS_REQUESTED",
  "BATCH_DELETE_WALLETS_SUCCEEDED",

  "SET_WALLET_FILTERS",
  "SET_WALLET_PAGE",
  "TOGGLE_WALLET_SELECTED",
  "SET_WALLET_SELECTION",
  "CLEAR_WALLET_SELECTION",

  "WALLET_ACTION_FAILED",
  "CLEAR_WALLET_ISSUES",
] as const);

export default walletActions;
