"""4Mica Python SDK — credit-layer infrastructure for the agentic economy.

Quickstart::

    from fourmica_sdk import Client, ConfigBuilder

    cfg = ConfigBuilder().network("base-sepolia").wallet_private_key("0x...").build()
    client = await Client.connect(cfg)
"""

from .auth import AuthClient, AuthNonceResponse, AuthSession, AuthTokens, SiweTemplate
from .client import Client
from .client.model import (
    Asset,
    AssetPosition,
    ClaimReceipt,
    DepositReceipt,
    PayReceipt,
    Route,
    StablecoinPosition,
    TokenRoute,
    WithdrawReceipt,
)
from .config import AuthConfig, Config, ConfigBuilder
from .errors import (
    AddressMismatchError,
    AuthError,
    CertificateMismatchError,
    ChainRpcUnavailableError,
    ClientError,
    ClientInitializationError,
    ConfigError,
    ContractError,
    Erc20AllowanceRequiredError,
    FacilitatorNotConfiguredError,
    FacilitatorRejectedError,
    FourMicaError,
    GuaranteeDomainMismatchError,
    InvalidParamsError,
    MissingTokenDomainSeparatorError,
    OutcomeUnknownError,
    PaymentError,
    Permit2AllowanceRequiredError,
    RevertedOnChainError,
    RpcError,
    SigningError,
    SponsorshipError,
    UnknownRevertError,
    UnsupportedGuaranteeVersionError,
    VerificationError,
    X402Error,
)
from .guarantee import decode_guarantee_claims, encode_guarantee_claims
from .models import (
    GUARANTEE_CLAIMS_VERSION,
    ZERO_ADDRESS,
    AssetBalanceInfo,
    BLSCert,
    ClearingParticipantProof,
    ClearingParticipantRole,
    ClearingSettlementAction,
    ClearingSettlementActionResponse,
    CorePublicParameters,
    GuaranteeVersionDomain,
    PaymentGuaranteeClaims,
    PaymentGuaranteeRequestClaims,
    PaymentSignature,
    RecipientPaymentInfo,
    SigningScheme,
    SupportedTokenInfo,
    SupportedTokensResponse,
    TxReceiptWaitOptions,
    UserSuspensionStatus,
    ValidationRequirement,
)
from .networks import NETWORKS, NetworkInfo, resolve_network_rpc_url
from .rpc import RpcProxy
from .signing import EvmSigner, LocalAccountSigner, PaymentSigner
from .x402 import (
    SCHEME_4MICA_CREDIT,
    FlowSigner,
    PaymentRequirementsExtra,
    PaymentRequirementsV1,
    PaymentRequirementsV2,
    SettlementReceipt,
    ValidationExtra,
    X402Flow,
    X402PaymentRequired,
    X402ResourceInfo,
    X402SettledPayment,
    X402SignedPayment,
)

__all__ = [
    "AddressMismatchError",
    "Asset",
    "AssetBalanceInfo",
    "AssetPosition",
    "AuthClient",
    "AuthConfig",
    "AuthError",
    "AuthNonceResponse",
    "AuthSession",
    "AuthTokens",
    "BLSCert",
    "CertificateMismatchError",
    "ChainRpcUnavailableError",
    "ClaimReceipt",
    "ClearingParticipantProof",
    "ClearingParticipantRole",
    "ClearingSettlementAction",
    "ClearingSettlementActionResponse",
    "Client",
    "ClientError",
    "ClientInitializationError",
    "Config",
    "ConfigBuilder",
    "ConfigError",
    "ContractError",
    "CorePublicParameters",
    "DepositReceipt",
    "Erc20AllowanceRequiredError",
    "EvmSigner",
    "FacilitatorNotConfiguredError",
    "FacilitatorRejectedError",
    "FlowSigner",
    "FourMicaError",
    "GUARANTEE_CLAIMS_VERSION",
    "GuaranteeDomainMismatchError",
    "GuaranteeVersionDomain",
    "InvalidParamsError",
    "LocalAccountSigner",
    "MissingTokenDomainSeparatorError",
    "NETWORKS",
    "NetworkInfo",
    "OutcomeUnknownError",
    "PayReceipt",
    "PaymentError",
    "PaymentGuaranteeClaims",
    "PaymentGuaranteeRequestClaims",
    "PaymentRequirementsExtra",
    "PaymentRequirementsV1",
    "PaymentRequirementsV2",
    "PaymentSignature",
    "PaymentSigner",
    "Permit2AllowanceRequiredError",
    "RecipientPaymentInfo",
    "RevertedOnChainError",
    "Route",
    "RpcError",
    "RpcProxy",
    "SCHEME_4MICA_CREDIT",
    "SettlementReceipt",
    "SigningError",
    "SigningScheme",
    "SiweTemplate",
    "SponsorshipError",
    "StablecoinPosition",
    "SupportedTokenInfo",
    "SupportedTokensResponse",
    "TokenRoute",
    "TxReceiptWaitOptions",
    "UnknownRevertError",
    "UnsupportedGuaranteeVersionError",
    "UserSuspensionStatus",
    "ValidationExtra",
    "ValidationRequirement",
    "VerificationError",
    "WithdrawReceipt",
    "X402Error",
    "X402Flow",
    "X402PaymentRequired",
    "X402ResourceInfo",
    "X402SettledPayment",
    "X402SignedPayment",
    "ZERO_ADDRESS",
    "decode_guarantee_claims",
    "encode_guarantee_claims",
    "resolve_network_rpc_url",
]
