import { mirrorKeys } from "@stores/utils";

const agentActions = mirrorKeys([
  "FETCH_AGENTS_REQUESTED",
  "FETCH_AGENTS_PENDING",
  "FETCH_AGENTS_SUCCEEDED",
  "FETCH_AGENTS_FAILED",

  "CREATE_AGENT_REQUESTED",
  "CREATE_AGENT_SUCCEEDED",
  "UPDATE_AGENT_REQUESTED",
  "UPDATE_AGENT_SUCCEEDED",
  "PUBLISH_AGENT_REQUESTED",
  "PUBLISH_AGENT_SUCCEEDED",
  "DELETE_AGENT_REQUESTED",
  "DELETE_AGENT_SUCCEEDED",
  "BATCH_DELETE_AGENTS_REQUESTED",
  "BATCH_DELETE_AGENTS_SUCCEEDED",

  "SET_AGENT_FILTERS",
  "SET_AGENT_PAGE",
  "TOGGLE_AGENT_SELECTED",
  "SET_AGENT_SELECTION",
  "CLEAR_AGENT_SELECTION",

  "AGENT_ACTION_FAILED",
  "CLEAR_AGENT_ISSUES",
] as const);

export default agentActions;
